from pydantic import BaseModel, Field
from typing import Optional
from uuid import UUID, uuid4
from datetime import datetime
from enum import Enum


class SessionStatus(str, Enum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    INTERRUPTED = "INTERRUPTED"


# ---------------------------------------------------------------------------
# Request Models
# ---------------------------------------------------------------------------

class SessionStartRequest(BaseModel):
    """
    Payload to start a new study session.

    client_session_id: A UUID v4 generated by the client BEFORE the request.
    This is the idempotency key — if the server already has a session with this
    ID, it returns the existing one instead of creating a duplicate.
    """
    client_session_id: UUID = Field(default_factory=uuid4)
    title: str = Field(..., min_length=1, max_length=255)
    topic_ids: list[UUID] = Field(default_factory=list)
    notes: Optional[str] = Field(default=None, max_length=5000)
    task_id: Optional[UUID] = None


# ---------------------------------------------------------------------------
# Response Models
# ---------------------------------------------------------------------------

class SessionResponse(BaseModel):
    """Full session object returned to the client."""
    id: UUID
    user_id: UUID
    title: str
    status: SessionStatus
    duration_seconds: int
    last_seen_at: datetime
    created_at: datetime
    updated_at: datetime
    task_id: Optional[UUID] = None


class SessionHeartbeatResponse(BaseModel):
    """Response payload for the heartbeat endpoint."""
    session_id: UUID
    status: SessionStatus
    server_time: datetime  # ISO 8601 UTC


HeartbeatResponse = SessionHeartbeatResponse


class PauseResponse(BaseModel):
    """Response payload for POST /sessions/{id}/pause."""
    session_id: UUID
    status: SessionStatus  # Will always be PAUSED
    paused_at: datetime    # Server UTC timestamp when pause was recorded
    pause_count: int       # Total number of pauses for this session


class ResumeResponse(BaseModel):
    """Response payload for POST /sessions/{id}/resume."""
    session_id: UUID
    status: SessionStatus          # Will always be ACTIVE
    resumed_at: datetime           # Server UTC timestamp when resume was recorded
    pause_duration_seconds: int    # Duration of the pause that just ended
    total_paused_seconds: int      # Cumulative paused time for this session


class EndResponse(BaseModel):
    """Response payload for POST /sessions/{id}/end."""
    session_id: UUID
    status: SessionStatus              # Will always be COMPLETED
    ended_at: datetime                 # Server UTC timestamp when session ended
    actual_duration_seconds: int       # Wall-clock minus paused time
    total_paused_seconds: int          # Sum of all pause durations
    pause_count: int                   # Number of pauses during this session
