"""add_checkpoint_columns_to_note_versions

Revision ID: 2c2db26b2198
Revises: fae38be5443c
Create Date: 2026-06-01 10:49:06.107103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c2db26b2198'
down_revision: Union[str, None] = 'fae38be5443c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_versions', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('note_versions', sa.Column('is_checkpoint', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_versions', 'is_checkpoint')
    op.drop_column('note_versions', 'name')
    # ### end Alembic commands ###
