"""add task_id to sessions

Revision ID: 6182ffcbab04
Revises: 17c106cb1985
Create Date: 2026-05-11 20:24:47.819572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6182ffcbab04'
down_revision: Union[str, None] = '17c106cb1985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('task_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'task_id')
    # ### end Alembic commands ###
