"""Add subject_id and task_id to Notes

Revision ID: dbd6bc88be81
Revises: 2026_05_16_2115
Create Date: 2026-05-17 20:15:26.288940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd6bc88be81'
down_revision: Union[str, None] = '2026_05_16_2115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'completion_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'INCOMPLETE'::character varying"))
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'soul_color_hex',
               existing_type=sa.VARCHAR(length=7),
               nullable=False,
               existing_server_default=sa.text("'#e2e8f0'::character varying"))
    op.alter_column('users', 'lite_mode_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'lite_mode_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'soul_color_hex',
               existing_type=sa.VARCHAR(length=7),
               nullable=True,
               existing_server_default=sa.text("'#e2e8f0'::character varying"))
    op.alter_column('users', 'display_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('tasks', 'completion_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'INCOMPLETE'::character varying"))
    # ### end Alembic commands ###
