"""add_ui_metadata_to_notes

Revision ID: f9d4e68d221f
Revises: dbd6bc88be81
Create Date: 2026-05-26 15:57:48.235925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9d4e68d221f'
down_revision: Union[str, None] = 'dbd6bc88be81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('ui_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('sessions', sa.Column('notes', sa.String(length=5000), nullable=True))
    op.add_column('sessions', sa.Column('topic_ids', sa.ARRAY(sa.UUID()), nullable=True))
    op.add_column('tasks', sa.Column('linked_note_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'linked_note_id')
    op.drop_column('sessions', 'topic_ids')
    op.drop_column('sessions', 'notes')
    op.drop_column('notes', 'ui_metadata')
    # ### end Alembic commands ###
